03 ABRIL 2026 
Script para hacer merge entre la tabla def de EXTREMÓFILOS con la nueva tabla con todas las PETases

In [1]:
import pandas as pd
import numpy as np

In [6]:
PETases = pd.read_excel("../tablas_PETases/total_PETases.xlsx", sheet_name="total_PETases")
PETases.head()

,qseqid,sseqid,pident,qlen,slen,length,qstart,qend,sstart,send,...,Isolation Source,true_extreme_environment,number_extr_environments,type_env_extr,environment,env comments,Final especie,true_micr_extreme,microorg_extremophile,microorg cooments
0,GCA_913061175.1_SRR3933257_bin.1_MetaBAT_v2.12...,P0173,71.111,314,319,315,1,313,4,318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AIK49165.1,P0111,81.768,214,205,181,34,214,25,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GCA_002345575.1_ASM234557v1_genomic_00658,P0176,73.733,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GCA_002345575.1_ASM234557v1_genomic_03654,P0174,67.662,201,201,201,1,201,1,201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MBX7275218.1,P0176,84.332,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
tabla = pd.read_excel("../EXTREMOPHILES_REFINED_31MAR2026_CompletnessContamination.xlsx", sheet_name="Genomes")
tabla.head()

,GTDB acc,NCBI acc,NCBI taxid,NCBI bioproject,Completeness (%),Contamination (%),Location,Source,Coordinates,Extremophile type,...,pH Growth,pH Optimum,Temperature Range,Temperature Growth,Temperature Optimum,Halophily Range,Halophily Growth,Halophily Optimum,DOI.1,PubMed ID2
0,GB_GCA_000008085.1,GCA_000008085.1,228908,PRJNA9599,98.72,0.38,none,none,none,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GB_GCA_000010565.1,GCA_000010565.1,370438,PRJDA19023,99.99,1.29,none,none,none,-,...,NaN,NaN,NaN,55,NaN,NaN,NaN,NaN,10.1099/00207713-52-5-1729;10.1128/aem.70.3.16...,12361280;15006786;16332758;16352836;21092234;2...
2,GB_GCA_000023725.1,GCA_000023725.1,531844,PRJNA38559,99.96,0.06,Antarctica: Vostok Station,glacial ice; 3519 m depth,none,psychro,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GB_GCA_000161755.1,GCA_000161755.1,501479,PRJNA37679,99.91,0.81,none,Spartina alterniflora (smooth cordgrass) detri...,none,halo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GB_GCA_000168735.1,GCA_000168735.1,394104,PRJNA16744,40.46,2.47,none,collected between 9deg N and 13deg N of the Ea...,none,thermo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Quiero copiar la información de los genomas de la tabla de extremófilos pero solo los genomas que están presentes en mi tabla de PETases.
Primero como prueba copio solo la localización

In [11]:
PETases = PETases.merge(tabla[["NCBI acc", "Location.1"]], on="NCBI acc", how="left")
PETases.head()

,qseqid,sseqid,pident,qlen,slen,length,qstart,qend,sstart,send,...,true_extreme_environment,number_extr_environments,type_env_extr,environment,env comments,Final especie,true_micr_extreme,microorg_extremophile,microorg cooments,Location.1
0,GCA_913061175.1_SRR3933257_bin.1_MetaBAT_v2.12...,P0173,71.111,314,319,315,1,313,4,318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Atlantic Sea
1,AIK49165.1,P0111,81.768,214,205,181,34,214,25,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Denmark
2,GCA_002345575.1_ASM234557v1_genomic_00658,P0176,73.733,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA:New York City
3,GCA_002345575.1_ASM234557v1_genomic_03654,P0174,67.662,201,201,201,1,201,1,201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA:New York City
4,MBX7275218.1,P0176,84.332,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,India

In [12]:
# Muevo los datos de la columna creada a mi columna Location
PETases["Location"] = PETases["Location.1"]
# Quito la columna extra
PETases = PETases.drop(columns=["Location.1"])
PETases.head()

,qseqid,sseqid,pident,qlen,slen,length,qstart,qend,sstart,send,...,Isolation Source,true_extreme_environment,number_extr_environments,type_env_extr,environment,env comments,Final especie,true_micr_extreme,microorg_extremophile,microorg cooments
0,GCA_913061175.1_SRR3933257_bin.1_MetaBAT_v2.12...,P0173,71.111,314,319,315,1,313,4,318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AIK49165.1,P0111,81.768,214,205,181,34,214,25,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GCA_002345575.1_ASM234557v1_genomic_00658,P0176,73.733,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GCA_002345575.1_ASM234557v1_genomic_03654,P0174,67.662,201,201,201,1,201,1,201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MBX7275218.1,P0176,84.332,218,218,217,1,217,1,217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Hacemos un merge con el resto de las columnas que faltan. 
Como me va a añadir las columnas de nuevo al estar repetidas voy a quitarlas primero.

In [13]:
PETases = PETases.drop(columns=[
    "Latitude", "Longitude", "Isolation Source",
    "true_extreme_environment", "number_extr_environments",
    "type_env_extr", "environment", "env comments",
    "Final especie",
    "true_micr_extreme",
    "microorg_extremophile",
    "microorg cooments"
], errors="ignore")

In [14]:
columnas = ["NCBI acc", "Latitude", "Longitude", "Isolation Source",
    "true_extreme_environment", "number_extr_environments",
    "type_env_extr", "environment", "env comments",
    "Final especie", "true_micr_extreme", "microorg_extremophile", "microorg cooments"]

PETases = PETases.merge(tabla[columnas], on="NCBI acc", how="left")
PETases.head(20)

,qseqid,sseqid,pident,qlen,slen,length,qstart,qend,sstart,send,...,Isolation Source,true_extreme_environment,number_extr_environments,type_env_extr,environment,env comments,Final especie,true_micr_extreme,microorg_extremophile,microorg cooments
0,GCA_913061175.1_SRR3933257_bin.1_MetaBAT_v2.12...,P0173,71.111,314,319,315,1,313,4,318,...,marine metagenome,no,NaN,NaN,NaN,NaN,uncultured Psychrobacter sp.,NaN,NaN,NaN
1,AIK49165.1,P0111,81.768,214,205,181,34,214,25,205,...,Rhizosphere,no,NaN,NaN,NaN,NaN,Bacillus atrophaeus subsp. globigii,NaN,NaN,NaN
2,GCA_002345575.1_ASM234557v1_genomic_00658,P0176,73.733,218,218,217,1,217,1,217,...,metal/plastic,no,NaN,NaN,NaN,NaN,Stutzerimonas stutzeri,NaN,NaN,NaN
3,GCA_002345575.1_ASM234557v1_genomic_03654,P0174,67.662,201,201,201,1,201,1,201,...,metal/plastic,no,NaN,NaN,NaN,NaN,Stutzerimonas stutzeri,NaN,NaN,NaN
4,MBX7275218.1,P0176,84.332,218,218,217,1,217,1,217,...,ice melting water from glacier site,extreme,monoextremophile,psychrophile,cryosphere,NaN,Pseudomonas sp. ERGC3:01,NaN,NaN,NaN
5,MBX7275838.1,P0174,72.139,201,201,201,1,201,1,201,...,ice melting water from glacier site,extreme,monoextremophile,psychrophile,cryosphere,NaN,Pseudomonas sp. ERGC3:01,NaN,NaN,NaN
6,GCA_021819735.1_ASM2181973v1_genomic_01925,P0159,72.587,280,281,259,14,266,2,259,...,acid mine drainage sediment,extreme,monoextremophile,acidophile,acid mine drainage,NaN,Deltaproteobacteria bacterium,NaN,NaN,NaN
7,GCA_021819735.1_ASM2181973v1_genomic_01926,P0159,75.290,279,281,259,14,265,2,259,...,acid mine drainage sediment,extreme,monoextremophile,acidophile,acid mine drainage,NaN,Deltaproteobacteria bacterium,NaN,NaN,NaN
8,GCA_029937415.1_ASM2993741v1_genomic_01175,P0137,78.599,283,264,257,27,283,4,260,...,hydrothermal plume,extreme,polyextremophile,"thermophile, piezophile",hydrothermal vent,NaN,Longimicrobiales bacterium,NaN,NaN,NaN
9,GCA_904846565.1_Psychrobacter_sp_CMS30_genomic...,P0173,62.687,334,319,335,1,333,4,318,...,poultry carcass,no,NaN,NaN,NaN,NaN,Psychrobacter sp. CMS30,NaN,NaN,NaN
10,MDP4525660.1,P0114,91.160,212,181,181,32,212,1,181,...,plastic in seawater,no,NaN,NaN,NaN,NaN,Bacillus halotolerans,NaN,NaN,NaN
11,MDP4526520.1,P0198,83.128,486,489,486,1,486,1,486,...,plastic in seawater,no,NaN,NaN,NaN,NaN,Bacillus halotolerans,NaN,NaN,NaN
12,MDP4526795.1,P0111,73.656,210,205,186,25,210,20,205,...,plastic in seawater,no,NaN,NaN,NaN,NaN,Bacillus halotolerans,NaN,NaN,NaN
13,MDP4526963.1,P0258,60.324,246,249,247,1,246,1,247,...,plastic in seawater,no,NaN,NaN,NaN,NaN,Bacillus halotolerans,NaN,NaN,NaN
14,PDM41723.1,P0258,68.016,247,249,247,2,247,1,247,...,hot spring,extreme,monoextremophile,thermophile,hot spring,NaN,Parageobacillus yumthangensis,NaN,NaN,NaN
15,MCX7662332.1,P0279,66.011,355,352,356,1,355,1,352,...,alkaline hot spring water,extreme,polyextremophile,"thermophile, alkalophile",hot spring,NaN,Tepidimonas fonticaldi,NaN,NaN,NaN
16,MCG8397989.1,P0111,82.873,214,205,181,34,214,25,205,...,hypersaline environment,extreme,monoextremophile,halophile,hypersaline environment (soil),NaN,Bacillus atrophaeus,NaN,NaN,NaN
17,MCG8398368.1,P0198,65.567,490,489,485,1,485,1,483,...,hypersaline environment,extreme,monoextremophile,halophile,hypersaline environment (soil),NaN,Bacillus atrophaeus,NaN,NaN,NaN
18,PJY99542.1,P0198,89.506,488,489,486,3,488,4,489,...,saltern sediments,extreme,monoextremophile,halophile,hypersaline environment (solar saltern),NaN,Bacillus vallismortis,NaN,NaN,NaN
19,PJZ00790.1,P0111,74.194,210,205,186,25,210,20,205,...,saltern sediments,extreme,monoextremophile,halophile,hypersaline environment (solar saltern),NaN,Bacillus vallismortis,NaN,NaN,NaN

In [15]:
# Guardamos el excel
PETases.to_excel("PETases_03ABR26.xlsx", index=False)